package com.bridgesense.app.model

import android.graphics.RectF

/**
 * A single object detection result from YOLOX-Small.
 * MOCK mode  → generated by MockDataProvider with realistic fake detections.
 * LIVE mode  → output from TFLite model running on Snapdragon Hexagon NPU.
 */
data class Detection(
    val label: String,           // e.g. "Crack", "Corrosion", "Spalling", "Deformation"
    val confidence: Float,       // 0.0 – 1.0
    val boundingBox: RectF,      // Normalized 0–1 coords (left, top, right, bottom)
    val classId: Int = 0,
    val isBridgeDamage: Boolean = true
) {
    val confidencePercent: Int   get() = (confidence * 100).toInt()
    val labelDisplay: String     get() = "$label ${confidencePercent}%"
}

/**
 * Full result from one YOLOX inference pass on a captured image.
 */
data class InferenceResult(
    val detections: List<Detection>,
    val inferenceTimeMs: Long,
    val imageWidth: Int,
    val imageHeight: Int,
    val isMock: Boolean = false
) {
    val hasDamage: Boolean     get() = detections.any { it.isBridgeDamage && it.confidence > 0.4f }
    val topDetection: Detection? get() = detections.maxByOrNull { it.confidence }

    val summaryText: String get() = when {
        isMock              -> "[MOCK] ${detections.size} detection(s) simulated"
        detections.isEmpty() -> "✓ No anomalies detected"
        hasDamage           -> "⚠ ${detections.count { it.isBridgeDamage }} anomaly/ies found"
        else                -> "${detections.size} object(s) detected"
    }

    val inferenceDisplay: String get() =
        if (isMock) "Mock mode" else "${inferenceTimeMs}ms on Hexagon NPU"
}
