package com.bridgesense.app.model

/**
 * Represents the real-time status of a single bridge sensor node.
 * In MOCK mode → values generated by MockDataProvider (no real hardware needed).
 * In LIVE mode → values arrive from the AI PC via WebSocket JSON messages.
 */
data class NodeStatus(
    val nodeId: Int,
    val nodeName: String,
    val status: NodeState,
    val vibration: Float,          // m/s²  — acceptable <2.0, warning 2–4, critical >4
    val tilt: Float,               // degrees — acceptable <1.5, warning 1.5–3, critical >3
    val temperature: Float,        // °C
    val batteryLevel: Int,         // 0–100 %
    val signalStrength: Int,       // 0–100 %
    val timestamp: Long = System.currentTimeMillis(),
    val aiConfidence: Float = 0f,  // AI model prediction confidence 0–1
    val predictionLabel: String = "Stable" // AI model output label from ONNX on AI PC
) {
    val isOnline: Boolean get() = status != NodeState.OFFLINE

    val lastUpdateFormatted: String get() {
        val diff = System.currentTimeMillis() - timestamp
        return when {
            diff < 60_000      -> "${diff / 1000}s ago"
            diff < 3_600_000   -> "${diff / 60_000}m ago"
            else               -> "${diff / 3_600_000}h ago"
        }
    }

    /** Battery icon character */
    val batteryIcon: String get() = when {
        batteryLevel > 75 -> "█"
        batteryLevel > 50 -> "▓"
        batteryLevel > 25 -> "▒"
        else              -> "░"
    }
}

enum class NodeState {
    NORMAL,    // All readings within safe thresholds
    WARNING,   // One or more readings in warning zone — monitor closely
    CRITICAL,  // Dangerous readings — alert dispatched, inspection needed
    OFFLINE    // Node not responding (dead battery / lost signal)
}
